### ISSUE TITLE
  Error "java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/compose/animation/AnimatedContentScope;"

### ISSUE THREAD

**Issue by coccalis** [hi-manshu/Kalendar#131]
Kalendar(
  currentDay = today,
    kalendarType = KalendarType.Firey,
    modifier = Modifier,
    showLabel = true,
    events = KalendarEvents(),
    kalendarHeaderTextKonfig = null,
    kalendarColors = KalendarColors.default(),
    kalendarDayKonfig = KalendarDayKonfig.default(),
    daySelectionMode = DaySelectionMode.Single,
    dayContent = null,
    headerContent = null,
    onDayClick = { selectedDay, events ->
        // Handle day click event
    },
    onRangeSelected = { selectedRange, events ->
        // Handle range selection event
    },
    onErrorRangeSelected = { error ->
        // Handle error
    })

**Comment by rohitjakhar** [comment]
same issue with me.

**Comment by hi-manshu** [comment]
Hey @rohitjakhar @coccalis ,
What is the Compose version are you on?

**Comment by rohitjakhar** [comment]
implementation platform('androidx.compose:compose-bom:2023.05.01')
kotlinCompilerExtensionVersion '1.4.6'

these.

**Comment by peporroncin** [comment]
Hi!,

Same issue with me. 

implementation platform('androidx.compose:compose-bom:2023.05.01')
kotlinCompilerExtensionVersion '1.4.1'

**Comment by hi-manshu** [comment]
Hey will check it later today.

**Comment by peporroncin** [comment]
Hi!

any updates?

**Comment by hi-manshu** [comment]
https://github.com/hi-manshu/Kalendar/releases/tag/v1.3.2
This should be fixed in this!

**Comment by peporroncin** [comment]
Hi,

I've updated version to 1.3.2 but the issue continues.

This is the logcat error:

java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Ljava/lang/String;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~McmB8z3HIZ136tq4KHO-9Q==/-51h2Mr0mubO16KkbvCby0w==/base.apk)
                                                                                                    	at com.himanshoe.kalendar.ui.component.header.KalendarHeaderKt.KalendarHeader(KalendarHeader.kt:87)
                                                                                                    	at com.himanshoe.kalendar.ui.firey.KalendarFireyKt.KalendarFirey(KalendarFirey.kt:118)
                                                                                                    	at com.himanshoe.kalendar.KalendarKt.Kalendar(Kalendar.kt:136)

**Comment by Jonakyll** [comment]
Hi, i am using the v1.3.2 and getting this error too:
`java.lang.NoSuchMethodError: No static method AnimatedContent(Ljava/lang/Object;Landroidx/compose/ui/Modifier;Lkotlin/jvm/functions/Function1;Landroidx/compose/ui/Alignment;Ljava/lang/String;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;II)V in class Landroidx/compose/animation/AnimatedContentKt; or its super classes (declaration of 'androidx.compose.animation.AnimatedContentKt' appears in /data/app/~~f0Ailj78fmB7zkVSDVaIUA==/com.mmmeat.mmmpro.dev-ezhCUn494SAO4JOv-1IAlQ==/base.apk)`

I am not using accompanist or bom
`val today = LocalDate.now()
    Kalendar(
        currentDay = today,
        kalendarType = KalendarType.Firey,
        modifier = Modifier,
        showLabel = true,
        events = KalendarEvents(),
        kalendarHeaderTextKonfig = null,
        kalendarColors = KalendarColors.default(),
        kalendarDayKonfig = KalendarDayKonfig.default(),
        daySelectionMode = DaySelectionMode.Single,
        dayContent = null,
        headerContent = null,
        onDayClick = { selectedDay, events ->
            // Handle day click event
        },
        onRangeSelected = { selectedRange, events ->
            // Handle range selection event
        },
        onErrorRangeSelected = { error ->
            // Handle error
        })`

**Comment by hi-manshu** [comment]
Did you try the above mentioned solution?

**Comment by Jonakyll** [comment]
yes, i put the versions mentioned but get the same error. I think this is related to compose-animation, so i tried to add the lib in my project, but still having the  java.lang.NoSuchMethodError: No static method AnimatedContent
